apiVersion: v1
kind: ReplicationController
metadata:
  name: klusterd
  labels:
    name: klusterd
spec:
  replicas: 1
  selector:
    name: klusterd
  template:
    metadata:
      name: klusterd
      labels:
        name: klusterd
    spec:
      containers:
      - name: klusterd
        image: registry-internal.cn-hangzhou.aliyuncs.com/lovepocky/klusterd:1.1
        ports:
        - containerPort: 2551
        env:
          - name: PEER_DISCOVERY_SERVICE
            value: klusterd-peers
